export const metadata = {
  title: "Terms of Service — Sorted",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="font-[family-name:var(--font-nunito)] text-3xl font-bold text-forest mb-2">
        Terms of Service
      </h1>
      <p className="text-sm text-charcoal/60 mb-8">Last updated: 20 March 2026</p>

      <div className="prose prose-sm max-w-none text-charcoal/80 space-y-6">
        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">1. Acceptance of Terms</h2>
        <p>
          By downloading, installing, or using the Sorted mobile application (&ldquo;the App&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use the App. These Terms constitute a legal agreement between you and MySorted Ltd (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;).
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">2. Description of Service</h2>
        <p>
          Sorted is a mobile application designed to help UK self-employed individuals track expenses, scan receipts, create invoices, log mileage, and estimate tax liabilities.
        </p>
        <p className="font-semibold">
          Important: Sorted is a tax estimation and record-keeping tool only. It does not provide financial, tax, or legal advice. Tax estimates generated by the App are approximations and should not be relied upon as a substitute for professional tax advice. We strongly recommend that you consult a qualified accountant or tax adviser for your Self Assessment filing.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">3. Eligibility</h2>
        <p>
          You must be at least 18 years old and a UK resident to use Sorted. By using the App, you represent and warrant that you meet these requirements.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">4. Subscription and Billing</h2>
        <p>Sorted is available as a subscription service at £4.99 per month.</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>A 7-day free trial is available for new users.</li>
          <li>Subscriptions are billed monthly through the Apple App Store or Google Play Store.</li>
          <li>Payment is charged to your Apple ID or Google account at confirmation of purchase.</li>
          <li>Your subscription automatically renews unless cancelled at least 24 hours before the end of the current billing period.</li>
          <li>You can manage and cancel your subscription through your device&apos;s App Store or Google Play settings.</li>
          <li>No refunds are provided for partial billing periods, though you may be entitled to a refund under Apple&apos;s or Google&apos;s refund policies.</li>
        </ul>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">5. Cancellation</h2>
        <p>
          You may cancel your subscription at any time through the Apple App Store or Google Play Store. Upon cancellation, you will retain access to the App until the end of your current billing period. After that, your access to premium features will cease, but you may still access and export your data.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">6. Your Responsibilities</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You are responsible for the accuracy of the data you enter into the App.</li>
          <li>You must not use the App for any unlawful purpose.</li>
          <li>You must not attempt to reverse-engineer, decompile, or disassemble the App.</li>
        </ul>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">7. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li>The App is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, whether express or implied.</li>
          <li>We do not guarantee the accuracy of tax estimates, OCR receipt scanning, or any calculations provided by the App.</li>
          <li>We shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App.</li>
          <li>Our total liability for any claim arising from or related to these Terms shall not exceed the amount you paid us in the 12 months preceding the claim.</li>
          <li>We are not liable for any penalties, interest, or additional tax charges resulting from reliance on the App&apos;s estimates.</li>
        </ul>
        <p>
          Nothing in these Terms excludes or limits our liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded or limited under English law.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">8. Intellectual Property</h2>
        <p>
          All intellectual property rights in the App, including but not limited to the software, design, graphics, text, and the &ldquo;Sorted&rdquo; brand, are owned by MySorted Ltd. You are granted a limited, non-exclusive, non-transferable licence to use the App for personal, non-commercial purposes in accordance with these Terms.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">9. Termination</h2>
        <p>
          We may suspend or terminate your access to the App at any time if you breach these Terms, without prior notice. Upon termination, you may request export of your data within 30 days by contacting{" "}
          <a href="mailto:support@mysorted.app" className="text-teal hover:underline">support@mysorted.app</a>.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">10. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of material changes via the App or email. Your continued use of the App after changes take effect constitutes acceptance of the revised Terms.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">11. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </p>

        <h2 className="font-[family-name:var(--font-nunito)] text-xl font-bold text-forest mt-8">12. Contact</h2>
        <p>
          If you have questions about these Terms, contact us at:
        </p>
        <p>
          MySorted Ltd<br />
          Email: <a href="mailto:support@mysorted.app" className="text-teal hover:underline">support@mysorted.app</a>
        </p>
      </div>
    </div>
  );
}
